# Generated by Django 5.2.5 on 2025-08-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='fitness_class',
            new_name='class_id',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('class_id', 'client_email')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client_email'], name='booking_client_email_idx'),
        ),
    ]
