# Generated by Django 5.2.5 on 2025-08-08 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_fitness_class_booking_class_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='class_id',
            new_name='fitness_class',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('fitness_class', 'client_email')},
        ),
    ]
