# Generated by Django 5.2.5 on 2025-08-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_class_id_booking_fitness_class_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='available_slots',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='total_slots',
            field=models.PositiveIntegerField(),
        ),
    ]
